server:
  port: 8888

logging:
  path: logs
  file: userManage.log

spring:
  application:
    name: userManager

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/maya
    username: root
    password: G2dhi@99
mybatis:
  type-aliases-package: com.appleieye.maya.model
  mapper-locations:
      - mapper/*